
const STORAGE_KEY="meal-flow-redesign-v1";
const DEFAULT_STATE={meals:[{id:"breakfast",name:"Breakfast",time:"09:00"},{id:"lunch",name:"Lunch",time:"14:00"},{id:"dinner",name:"Dinner",time:"19:00"}],snackMode:"vegetables",snackTime:"16:30",water:0,reminders:false,sound:false};
let state=loadState();
const els={greeting:document.getElementById("greeting"),waterCount:document.getElementById("waterCount"),hydrateBtn:document.getElementById("hydrateBtn"),nextMealName:document.getElementById("nextMealName"),nextMealTime:document.getElementById("nextMealTime"),countdown:document.getElementById("countdown"),ringProgress:document.getElementById("ringProgress"),ateButton:document.getElementById("ateButton"),skipButton:document.getElementById("skipButton"),snackTitle:document.getElementById("snackTitle"),snackHint:document.getElementById("snackHint"),mealList:document.getElementById("mealList"),mealTemplate:document.getElementById("mealItemTemplate"),addMealBtn:document.getElementById("addMealBtn"),snackRadios:document.querySelectorAll("input[name='snackMode']"),customSnackField:document.getElementById("customSnackField"),snackTimeInput:document.getElementById("snackTimeInput"),remindersToggle:document.getElementById("remindersToggle"),soundToggle:document.getElementById("soundToggle"),settingsPanel:document.getElementById("settingsPanel"),openSettingsMobile:document.getElementById("openSettingsMobile")};
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2)}
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return saved?{...DEFAULT_STATE,...saved}:structuredClone(DEFAULT_STATE)}catch{return structuredClone(DEFAULT_STATE)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function minutesFromTime(time){const[h,m]=time.split(":").map(Number);return h*60+m}
function timeToDate(time,offset=0){const[h,m]=time.split(":").map(Number);const d=new Date();d.setDate(d.getDate()+offset);d.setHours(h,m,0,0);return d}
function formatClock(date){return date.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}
function formatDuration(ms){const s=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(s/3600)).padStart(2,"0")}:${String(Math.floor(s%3600/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function getSchedule(){const list=state.meals.map(m=>({...m,type:"meal"}));if(state.snackMode==="custom")list.push({id:"snack",name:"Snack",time:state.snackTime,type:"snack"});return list.sort((a,b)=>minutesFromTime(a.time)-minutesFromTime(b.time))}
function getNextEvent(){const now=new Date();const today=getSchedule().map(i=>({...i,date:timeToDate(i.time)}));return today.find(i=>i.date>now)||(()=>{const first=getSchedule()[0];return {...first,date:timeToDate(first.time,1)}})()}
function getPreviousEvent(){const now=new Date();const schedule=getSchedule();const today=schedule.map(i=>({...i,date:timeToDate(i.time)}));const past=today.filter(i=>i.date<=now);if(past.length)return past[past.length-1];const last=schedule[schedule.length-1];return {...last,date:timeToDate(last.time,-1)}}
function setGreeting(){const h=new Date().getHours();els.greeting.textContent=`${h<12?"Good morning":h<18?"Good afternoon":"Good evening"}, Victor!`}
function updateSnackText(next){if(next.type==="snack"){els.snackTitle.textContent="Snack window is next";els.snackHint.textContent="Keep it planned and light.";return}if(state.snackMode==="none"){els.snackTitle.textContent="No snacks right now";els.snackHint.textContent="Water, tea or coffee are okay.";return}if(state.snackMode==="vegetables"){els.snackTitle.textContent="Vegetables are okay";els.snackHint.textContent="Water, tea, cucumber, tomato or pepper.";return}els.snackTitle.textContent="Stay with the plan";els.snackHint.textContent="Wait for the next scheduled meal or snack."}
function updateTimer(){const now=new Date(),next=getNextEvent(),prev=getPreviousEvent();els.nextMealName.textContent=next.name;els.nextMealTime.textContent=`${next.date.toDateString()===now.toDateString()?"Today":"Tomorrow"} at ${formatClock(next.date)}`;els.countdown.textContent=formatDuration(next.date-now);const progress=Math.min(1,Math.max(0,(now-prev.date)/(next.date-prev.date)));els.ringProgress.style.strokeDasharray=`${Math.round(progress*560)} 704`;els.ateButton.innerHTML=next.type==="snack"?"<span>✓</span>Snack done":"<span>✓</span>I ate";updateSnackText(next)}
function renderMeals(){els.mealList.innerHTML="";state.meals.sort((a,b)=>minutesFromTime(a.time)-minutesFromTime(b.time)).forEach(meal=>{const node=els.mealTemplate.content.cloneNode(true),item=node.querySelector(".meal-item"),name=node.querySelector(".meal-name-input"),time=node.querySelector(".meal-time-input"),remove=node.querySelector(".meal-remove");name.value=meal.name;time.value=meal.time;name.addEventListener("change",()=>{meal.name=name.value.trim()||"Meal";saveState();updateTimer()});time.addEventListener("change",()=>{meal.time=time.value||meal.time;saveState();renderMeals();updateTimer()});remove.addEventListener("click",()=>{if(state.meals.length<=1)return;state.meals=state.meals.filter(i=>i.id!==meal.id);saveState();renderMeals();updateTimer()});item.dataset.mealId=meal.id;els.mealList.appendChild(node)})}
function syncControls(){els.waterCount.textContent=state.water;els.snackTimeInput.value=state.snackTime;els.remindersToggle.checked=state.reminders;els.soundToggle.checked=state.sound;els.snackRadios.forEach(r=>r.checked=r.value===state.snackMode);els.customSnackField.classList.toggle("is-hidden",state.snackMode!=="custom")}
function flash(title,hint="Great. Now return to focus."){els.snackTitle.textContent=title;els.snackHint.textContent=hint;setTimeout(updateTimer,1800)}
els.hydrateBtn.addEventListener("click",()=>{state.water=state.water>=6?0:state.water+1;saveState();syncControls()});
els.ateButton.addEventListener("click",()=>flash(`${getNextEvent().name} marked as done`));
els.skipButton.addEventListener("click",()=>flash(`${getNextEvent().name} skipped`));
els.addMealBtn.addEventListener("click",()=>{state.meals.push({id:uid(),name:"Meal",time:"12:00"});saveState();renderMeals();updateTimer()});
els.snackRadios.forEach(r=>r.addEventListener("change",()=>{state.snackMode=r.value;saveState();syncControls();updateTimer()}));
els.snackTimeInput.addEventListener("change",()=>{state.snackTime=els.snackTimeInput.value||"16:30";saveState();updateTimer()});
els.remindersToggle.addEventListener("change",async()=>{state.reminders=els.remindersToggle.checked;if(state.reminders&&"Notification"in window&&Notification.permission==="default")await Notification.requestPermission();saveState()});
els.soundToggle.addEventListener("change",()=>{state.sound=els.soundToggle.checked;saveState()});
els.openSettingsMobile.addEventListener("click",()=>els.settingsPanel.classList.toggle("is-open"));
document.addEventListener("keydown",e=>{if(e.key==="Escape")els.settingsPanel.classList.remove("is-open")});
setGreeting();renderMeals();syncControls();updateTimer();setInterval(updateTimer,1000);setInterval(setGreeting,60000);
